version: "3"

services:
  parser:
    build:
      context: .
      dockerfile: parser.Dockerfile
    image: int_parser:latest
    restart: always
    depends_on:
      - redis
    ports:
      - "4000"
    env_file:
      - .env
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.parser.rule=Host(`parser.dishcovery-app.com`)"
      - "traefik.http.routers.parser.entrypoints=websecure"
      - "traefik.http.routers.parser.tls.certResolver=letsencrypt"
  redis:
    image: redis
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis:/data
    networks:
      - dokploy-network

volumes:
  redis:

networks:
  dokploy-network:
    external: true
